import {StyleSheet} from 'react-native';
import colors from '../../../../shared/styling/lightModeColors';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    padding: 5,
    flex: 1,
    position: 'relative',
    alignItems: 'center',
  },
  card: {
    borderRadius: 12,
    width: '95%',
    minHeight: 100,
    padding: 5,
    backgroundColor: colors.white,
    elevation: 5,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  innercontainer: {
    flex: 1,
    paddingHorizontal: 1,
  },
  image: {
    maxWidth: 60,
    maxHeight: 60,
    minWidth: 60,
    minHeight: 60,
    borderRadius: 90,
    marginRight: 1,
    borderWidth: 1,
    borderColor: 'grey',
    elevation: 6,
    marginBottom: 5,
  },
  logoContainer: {
    maxWidth: 60,
    maxHeight: 60,
    borderRadius: 90,
    backgroundColor: colors.light,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 1,
    borderWidth: 1,
    borderColor: colors.medium,
    elevation: 6,
  },
  logoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.dark,
  },
  rowGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  heading: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  rightMenu: {
    position: 'absolute',
    top: 15,
    right: 0,
    height: '88%',
    width: 35,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownOutside: {
    position: 'absolute',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.medium,
    borderRadius: 8,
    width: 160,
    zIndex: 9999,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 6,
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.light,
  },
  dropdownText: {
    fontSize: 14,
    color: colors.dark,
  },
  statusBadge: {
    position: 'absolute',
    top: 0,
    right: 40,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 10,
  },
  statusText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 10,
  },
});

export default styles;
